HW07
Otus-DevOps-2017-11/OSidorenkov_infra pull request #3
Opened 2018-01-07 20:39 UTC by OSidorenkov

2018-01-15 17:24 UTC, Nklya requested changes
Добрый вечер.

Олег, в принципе условия дз выполнены, но есть несколько проблем:
1. Все переменные, которые ты задаешь в variables.example.json, должны быть указаны в секции variables https://www.packer.io/docs/templates/user-variables.html 
Это позволит задавать значения по умолчанию и не пихать все в variables.json
2. Форматирование сбито в ubuntu16.json

2018-01-15 17:24 UTC, Nklya commented on packer/ubuntu16.json
> +{
Что-то здесь печальное с форматированием.

2018-01-15 17:25 UTC, Nklya commented
И заполни описание этого PR.

P.S. *Не мерж* в мастер пока что следующий PR.

2018-01-16 07:20 UTC, OSidorenkov commented on packer/ubuntu16.json
> +{
А что именно не так? json рабочий, отступов нет?

2018-01-16 07:21 UTC, Nklya commented on packer/ubuntu16.json
> +{
Да, отступов нет. Выглядит дико.

2018-01-16 07:35 UTC, OSidorenkov commented on packer/ubuntu16.json
> +{
про переменные я не очень понял, ты имеешь в виду вводить в шаблон пакера секцию variables и там их определять?

2018-01-16 07:41 UTC, Nklya commented on packer/ubuntu16.json
> +{
Да, в шаблон пакера. 
И описание Pr заполни

2018-01-16 07:42 UTC, OSidorenkov commented on packer/ubuntu16.json
> +{
Форматирование добавил в packer/ubuntu16.json

2018-01-16 10:28 UTC, Nklya requested changes
Как я уже писал, нужно добавить секцию variables в шаблоны пакера. Пример https://github.com/Otus-DevOps-2017-11/VARyumin_infra/pull/3/files#diff-21d672a9538f283c2dcdeb2902016cd6R1

Тогда те переменные, которые имеют значения по умолчанию, можно не указывать в variables.example.json

2018-01-16 11:01 UTC, OSidorenkov commented
Добавил переменные в шаблон пакера.
https://github.com/Otus-DevOps-2017-11/OSidorenkov_infra/pull/3/commits/c7c7cc043882d9e9b3e9648b3999e929fb7f4cc5

2018-01-16 11:10 UTC, Nklya requested changes
Не совсем то.
Комментарии ниже.

2018-01-16 11:10 UTC, Nklya commented on packer/immutable.json
> +{
variables нужно задать в обоих шаблонах

2018-01-16 11:10 UTC, Nklya commented on packer/variables.example.json
> +{
Variables нужно задать в обоих шаблонах.
Задавать нужно все переменные. 
Как минимум proj_id и sif должны быть обязательными.

В variables.example.json должны быть указаны обязательные переменные, либо те, которые переопределяют дефолтные значения.

2018-01-16 12:28 UTC, Nklya requested changes
1. Обязательные переменные в шаблоне должны быть равны null
2. Все переменные из variables.example.json должны быть в секции variables. После этого те переменные, которые не нужно переопределять, выкидываещь из variables.example.json.

2018-01-16 12:28 UTC, Nklya commented on packer/ubuntu16.json
> +      "proj_id": "infra-190310",
Обязательная переменная означает что в шаблоне пакера она должна равнятся null.
Пример https://github.com/Otus-DevOps-2017-11/AndreyErmilov_infra/pull/3/files#diff-21d672a9538f283c2dcdeb2902016cd6R3

2018-01-16 12:28 UTC, Nklya commented on packer/immutable.json
> +      "proj_id":"infra-190310",
Обязательная переменная означает что в шаблоне пакера она должна равнятся null.
Пример https://github.com/Otus-DevOps-2017-11/AndreyErmilov_infra/pull/3/files#diff-21d672a9538f283c2dcdeb2902016cd6R3

2018-01-16 13:25 UTC, Nklya approved these changes
Да.
Теперь относительно нормально.

2018-01-16 15:59 UTC, merged