Ansible 1: HW10
Otus-DevOps-2017-11/OSidorenkov_infra pull request #6
Opened 2018-01-14 19:19 UTC by OSidorenkov

Произведена установка ansible >=2.4.
Созданы 3 одинаковых инвентори файла в 3 форматах:
* ini
* yml
* json

Выполнены все команды для проверки конфигурации stage серверов. Почувствовал разницу между модулями shell, command и service.

2018-01-18 12:17 UTC, Nklya requested changes
Ревью после фикса и мержа предыдущего.

2018-02-05 09:17 UTC, OSidorenkov commented
Пофиксил предыдущий PR

2018-02-05 12:19 UTC, Nklya approved these changes
Добрый день.

Олег, базовое задание ок.

По дополнительному не то.
Комментарии ниже.

2018-02-05 12:21 UTC, Nklya commented
Ссылка на доку ведет на https://medium.com/@Nklya/динамическое-инвентори-в-ansible-9ee880d540d6
<img width="945" alt="screen shot 2018-01-30 at 00 26 52" src="https://user-images.githubusercontent.com/26086394/35804293-39b69418-0a88-11e8-8539-3f488fed4e4a.png">

2018-02-05 18:11 UTC, merged